import './globals.css';
import { DM_Sans } from 'next/font/google';
import { Navbar } from '@/components/Navbar';
import clsx from 'clsx';
import { Banner } from '@/components/Banner';
import { ThemeProvider } from '@/components/theme-provider';
import { Footer } from '@/components/Footer';
import { ToastContainer } from 'react-toastify';
import StoreProvider from '@/components/StoreProvider';

const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Event Commerce',
  description: 'FRONTEND GENERATED BY NEXT.JS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={clsx(dmSans.className, 'antialiased')}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>

            <Navbar />

            <ToastContainer
              position="top-center"
              autoClose={8000}
              closeOnClick
              draggable
            />

            <div className="">{children}</div>

            <Footer />
          </StoreProvider>

          <Banner />

        </ThemeProvider>
      </body>
    </html>
  );
}